// Pie Charts — Data Interpretation (frontend-rendered, exam-grade)
export default {
  intro:
    "A pie chart shows how one whole is split into parts. The full circle is 360 degrees and also equals 100 percent of the total, so every slice can be read three ways: as a percentage, as an angle in degrees, or as an actual value (rupees, people, units). The single skill that decides most placement pie questions is converting freely between these three. In TCS NQT, Infosys, Wipro and CAT-style sets you will see single-pie value questions, angle questions, combined and ratio-of-slice questions, pie-plus-table problems where you must first find the total from one known value, and two-pie comparisons where the two pies have DIFFERENT totals. This lesson drills every one of those.",

  howToRead: [
    { step: "The whole circle = total = 360 degrees = 100 percent", detail: "Whatever the pie represents (total students, total revenue), that number maps to the complete 360 degrees or the complete 100 percent. Find or note the total first." },
    { step: "1 percent = 3.6 degrees", detail: "Because 100 percent spreads over 360 degrees, each 1 percent is 360/100 = 3.6 degrees. So angle = percent x 3.6, and percent = angle / 3.6." },
    { step: "Percent to value: multiply by the total", detail: "Value of a slice = (percent / 100) x total. Example: 20 percent of 2400 = 480. This step is where most marks are lost when people forget to multiply by the total." },
    { step: "Degrees to value: value = (angle / 360) x total", detail: "If the pie is labelled in degrees, convert straight to value with angle/360, or first go angle/3.6 to get percent. Example: a 72 degree slice of Rs 43200 = 72/360 x 43200 = Rs 8640." },
    { step: "Value to percent to angle (reverse)", detail: "Given a slice value, percent = slice/total x 100, then angle = percent x 3.6. Used in pie-plus-table problems and 'which slice is this' questions." },
    { step: "Comparing two pies: never compare percentages directly", detail: "Two pies usually have different totals. 30 percent of a small total can be less than 20 percent of a large total. Always convert both to actual values before you compare or add across pies." },
  ],

  speedTips: [
    "Write the total in the margin the instant you see the chart. Every value question is (percent/100) x total.",
    "Memorise the angle anchors: 10 percent = 36 deg, 25 percent = 90 deg, 50 percent = 180 deg, 100 percent = 360 deg. Interpolate the rest.",
    "For combined slices, add the percentages (or angles) first, then convert once. Do not convert each slice and add.",
    "For 'A is what percent more than B' use (A - B)/B x 100, dividing by B (the base), not by the total.",
    "Ratio of two slices equals the ratio of their percentages equals the ratio of their angles. The total cancels, so you can skip it entirely for pure ratios.",
    "In pie-plus-table problems, the one given value unlocks everything: total = given value / (its percent as a decimal). Compute the total once, then all other slices.",
    "When the total changes but percentages stay the same, a slice scales with the total: new value = old percent x new total.",
  ],

  traps: [
    "Confusing degrees with percent. A slice of 90 degrees is 25 percent, NOT 90 percent. Divide by 3.6 before treating a degree figure as a percentage.",
    "Forgetting to multiply by the total. A 15 percent slice is not 15; it is 15 percent of the total value.",
    "Comparing two pies by percentage alone. Different totals mean a bigger percentage can still be a smaller amount. Convert to values first.",
    "In 'X percent more than Y', dividing the difference by the total or by X instead of by Y. The base is always the thing you are compared against (Y).",
    "Reading a combined-slice question as a single slice. 'Fiction and Comics together' means add both percentages before converting.",
    "Assuming both pies list the same total when only percentages are shown. Read the note or table for each pie's own total.",
  ],

  questionTypes: [
    { name: "Single-slice value", how: "value = (percent/100) x total. If the slice is in degrees, value = (angle/360) x total." },
    { name: "Angle of a slice", how: "angle = percent x 3.6. Or angle = (slice value / total) x 360." },
    { name: "Combined slices", how: "Add the percentages (or angles) of the wanted slices, then convert the sum to a value once." },
    { name: "Ratio of two slices", how: "Ratio = percent A : percent B = angle A : angle B = value A : value B. Total cancels; reduce to lowest terms." },
    { name: "'A is what percent more/less than B'", how: "(A - B)/B x 100 using values (or percentages, since the total cancels). Divide by the base slice B." },
    { name: "Find total from one known value, then another slice", how: "total = given value / (its percent/100). Then target slice = (its percent/100) x total." },
    { name: "Percent change when the total changes", how: "Percentages fixed, total changes: new slice value = old percent x new total. Total change itself = (new - old)/old x 100." },
    { name: "Two-pie comparison", how: "Convert each pie's slices to values using that pie's own total, then add or compare across the two pies." },
    { name: "Slice value as percent of the OTHER pie's total", how: "Compute the slice value from its own pie, then divide by the other pie's total x 100. A classic cross-total trap." },
  ],

  visual: {
    note: "Monthly budget of a student, total = Rs 30000. Slice values shown are in rupees. Rent 9000 (30 pct, 108 deg), Food 6000 (20 pct, 72 deg), Savings 4500 (15 pct, 54 deg), Others 5100 (17 pct, 61.2 deg), Transport 3000 (10 pct, 36 deg), Entertainment 2400 (8 pct, 28.8 deg).",
    charts: [
      { type: "pie", slices: [
        { label: "Rent", value: 9000 },
        { label: "Food", value: 6000 },
        { label: "Others", value: 5100 },
        { label: "Savings", value: 4500 },
        { label: "Transport", value: 3000 },
        { label: "Entertainment", value: 2400 },
      ] },
    ],
  },

  worked: {
    question: "In the budget pie above (total Rs 30000), Rent is Rs 9000. What percent of the budget is Rent, and what is the angle of the Rent slice?",
    steps: [
      { action: "Find the percent: 9000 / 30000 x 100", why: "Percent of a slice = slice value / total x 100." },
      { action: "9000 / 30000 = 0.30, so 30 percent", why: "Rent takes 30 percent of the monthly budget." },
      { action: "Convert to degrees: 30 x 3.6", why: "1 percent = 3.6 degrees, so angle = percent x 3.6." },
      { action: "30 x 3.6 = 108 degrees", why: "The Rent slice spans 108 degrees of the circle." },
    ],
    answer: "Rent = 30 percent of the budget, and its slice angle = 108 degrees.",
  },

  sheets: [
    {
      title: "Sheet 1 — Reading a single pie (percentages)",
      difficulty: "Easy",
      note: "Distribution of 2400 students of an engineering college by branch. Slice values shown are percentages (they add to 100). Total students = 2400.",
      charts: [
        { type: "pie", slices: [
          { label: "Computer Science", value: 25 },
          { label: "Mechanical", value: 20 },
          { label: "Electrical", value: 18 },
          { label: "Civil", value: 15 },
          { label: "Electronics", value: 12 },
          { label: "Others", value: 10 },
        ] },
      ],
      questions: [
        { question: "What is the angle (in degrees) of the Computer Science slice?", answer: "90 degrees",
          solution: "Angle = percent x 3.6 = 25 x 3.6 = 90 degrees." },
        { question: "How many students are in the Mechanical branch?", answer: "480 students",
          solution: "Value = 20 percent of 2400 = 0.20 x 2400 = 480." },
        { question: "How many students are in Computer Science and Electrical together?", answer: "1032 students",
          solution: "Combined percent = 25 + 18 = 43 percent. 43 percent of 2400 = 0.43 x 2400 = 1032 (600 + 432)." },
        { question: "Which branch has exactly 288 students?", answer: "Electronics",
          solution: "288 / 2400 = 0.12 = 12 percent, which is the Electronics slice." },
        { question: "What is the ratio of Civil students to Electronics students?", answer: "5 : 4",
          solution: "Ratio = 15 : 12 (percents cancel the total) = 5 : 4. Check values: 360 : 288 = 5 : 4." },
        { question: "What is the angle of the Others slice?", answer: "36 degrees",
          solution: "Angle = 10 x 3.6 = 36 degrees." },
        { question: "How many more students are in Computer Science than in Civil?", answer: "240 students",
          solution: "Difference = (25 - 15) = 10 percent of 2400 = 240 (600 - 360)." },
        { question: "Electrical students are what percent of the total?", answer: "18 percent",
          solution: "Electrical is the 18 percent slice directly; 432 / 2400 x 100 = 18 percent." },
      ],
    },

    {
      title: "Sheet 2 — Pie labelled in degrees, plus a changing total",
      difficulty: "Medium",
      note: "Monthly expenditure of a family shown in DEGREES (the slice values are angles, they add to 360). Total monthly expenditure = Rs 43200. Food 108, Rent 72, Savings 54, Education 54, Transport 36, Miscellaneous 36.",
      charts: [
        { type: "pie", slices: [
          { label: "Food", value: 108 },
          { label: "Rent", value: 72 },
          { label: "Savings", value: 54 },
          { label: "Education", value: 54 },
          { label: "Transport", value: 36 },
          { label: "Miscellaneous", value: 36 },
        ] },
      ],
      questions: [
        { question: "How much (in rupees) is spent on Food?", answer: "Rs 12960",
          solution: "Food = (108/360) x 43200 = 0.30 x 43200 = Rs 12960 (Food is 108/3.6 = 30 percent)." },
        { question: "What percent of the budget is Rent?", answer: "20 percent",
          solution: "Percent = angle / 3.6 = 72 / 3.6 = 20 percent." },
        { question: "How much more is spent on Education than on Transport?", answer: "Rs 2160",
          solution: "Difference in angle = 54 - 36 = 18 degrees = 5 percent. 5 percent of 43200 = Rs 2160 (6480 - 4320)." },
        { question: "What is the ratio of Food expenditure to Savings expenditure?", answer: "2 : 1",
          solution: "Ratio of angles = 108 : 54 = 2 : 1 (the total cancels)." },
        { question: "How much is spent on Transport and Miscellaneous combined?", answer: "Rs 8640",
          solution: "Combined angle = 36 + 36 = 72 degrees = 20 percent. 20 percent of 43200 = Rs 8640 (4320 + 4320)." },
        { question: "Next month the total expenditure rises to Rs 50400 while the percentages stay the same. What is the new Food expenditure?", answer: "Rs 15120",
          solution: "Food stays 30 percent. New value = 0.30 x 50400 = Rs 15120." },
        { question: "Savings is what percent more than Transport?", answer: "50 percent",
          solution: "Savings = Rs 6480, Transport = Rs 4320. (6480 - 4320)/4320 x 100 = 2160/4320 x 100 = 50 percent." },
        { question: "What is the combined angle of the Rent and Education slices?", answer: "126 degrees",
          solution: "72 + 54 = 126 degrees." },
      ],
    },

    {
      title: "Sheet 3 — Pie plus a table (find the total first)",
      difficulty: "Hard",
      note: "A bookstore's sales split by genre, shown as percentages (they add to 100). The table gives the actual number sold for ONE genre. Use it to find the total, then answer the rest. Fiction 28, Non-fiction 22, Academic 18, Children 12, Comics 12, Others 8.",
      charts: [
        { type: "pie", slices: [
          { label: "Fiction", value: 28 },
          { label: "Non-fiction", value: 22 },
          { label: "Academic", value: 18 },
          { label: "Children", value: 12 },
          { label: "Comics", value: 12 },
          { label: "Others", value: 8 },
        ] },
        { type: "table", caption: "Known reference value", columns: ["Genre", "Books sold"], rows: [["Academic", 900]], highlightCol: 1 },
      ],
      questions: [
        { question: "What is the total number of books sold?", answer: "5000 books",
          solution: "Academic = 18 percent = 900 books. Total = 900 / 0.18 = 5000." },
        { question: "How many Fiction books were sold?", answer: "1400 books",
          solution: "Fiction = 28 percent of 5000 = 0.28 x 5000 = 1400." },
        { question: "How many Non-fiction and Children books were sold together?", answer: "1700 books",
          solution: "Combined = (22 + 12) = 34 percent of 5000 = 0.34 x 5000 = 1700 (1100 + 600)." },
        { question: "Fiction sales are what percent more than Non-fiction sales?", answer: "27.27 percent (approx)",
          solution: "Fiction = 1400, Non-fiction = 1100. (1400 - 1100)/1100 x 100 = 300/1100 x 100 = 27.27 percent approx." },
        { question: "What is the angle of the Fiction slice?", answer: "100.8 degrees",
          solution: "Angle = 28 x 3.6 = 100.8 degrees." },
        { question: "What is the ratio of Comics sold to Children books sold?", answer: "1 : 1",
          solution: "Both are 12 percent, so 600 : 600 = 1 : 1." },
        { question: "How many more Fiction books than Academic books were sold?", answer: "500 books",
          solution: "Fiction 1400 - Academic 900 = 500 (or (28 - 18) = 10 percent of 5000 = 500)." },
        { question: "Academic, Comics and Others together make up what fraction of total sales?", answer: "19/50",
          solution: "Combined percent = 18 + 12 + 8 = 38 percent = 38/100 = 19/50 (that is 1900 out of 5000)." },
      ],
    },

    {
      title: "Sheet 4 — Two-pie comparison (different totals)",
      difficulty: "Hard",
      note: "Region-wise revenue of two companies. LEFT pie = Company X, total revenue Rs 80 lakh. RIGHT pie = Company Y, total revenue Rs 120 lakh. Both pies show percentages. Because the totals differ, convert every slice to rupees before comparing or adding across the two.",
      charts: [
        { type: "pie", slices: [
          { label: "North", value: 30 },
          { label: "South", value: 25 },
          { label: "East", value: 20 },
          { label: "West", value: 15 },
          { label: "Central", value: 10 },
        ] },
        { type: "pie", slices: [
          { label: "North", value: 20 },
          { label: "South", value: 30 },
          { label: "West", value: 25 },
          { label: "East", value: 15 },
          { label: "Central", value: 10 },
        ] },
      ],
      questions: [
        { question: "What is Company X's revenue from the North region?", answer: "Rs 24 lakh",
          solution: "North of X = 30 percent of 80 = 0.30 x 80 = Rs 24 lakh." },
        { question: "Which company earns more from the South region, and by how much?", answer: "Company Y, by Rs 16 lakh",
          solution: "X South = 25 percent of 80 = 20 lakh. Y South = 30 percent of 120 = 36 lakh. Y is higher by 36 - 20 = Rs 16 lakh." },
        { question: "What is the combined East-region revenue of both companies?", answer: "Rs 34 lakh",
          solution: "X East = 20 percent of 80 = 16 lakh. Y East = 15 percent of 120 = 18 lakh. Total = 16 + 18 = Rs 34 lakh." },
        { question: "North is 30 percent for Company X but 20 percent for Company Y. Whose North revenue is actually higher?", answer: "Neither, they are equal (Rs 24 lakh each)",
          solution: "X North = 30 percent of 80 = 24 lakh. Y North = 20 percent of 120 = 24 lakh. Equal, despite the different percentages. This is why you must convert to values." },
        { question: "What is the total West-region revenue of both companies together?", answer: "Rs 42 lakh",
          solution: "X West = 15 percent of 80 = 12 lakh. Y West = 25 percent of 120 = 30 lakh. Total = 12 + 30 = Rs 42 lakh." },
        { question: "Company Y's South revenue is what percent of Company X's TOTAL revenue?", answer: "45 percent",
          solution: "Y South = 30 percent of 120 = 36 lakh. X total = 80 lakh. 36 / 80 x 100 = 45 percent." },
        { question: "What is the ratio of Company X's Central revenue to Company Y's Central revenue?", answer: "2 : 3",
          solution: "X Central = 10 percent of 80 = 8 lakh. Y Central = 10 percent of 120 = 12 lakh. Ratio = 8 : 12 = 2 : 3." },
        { question: "By what percent is Company Y's total revenue greater than Company X's total revenue?", answer: "50 percent",
          solution: "(120 - 80)/80 x 100 = 40/80 x 100 = 50 percent." },
      ],
    },
  ],
}
