spring.application.name=Student-BackEnd
server.port=8080

spring.data.mongodb.uri=mongodb+srv://manmadhajayamangala777_db_user:manmadhA%2C8688@free-database.lfnuahd.mongodb.net/learnData_db?retryWrites=true&w=majority&appName=Free-Database
spring.data.mongodb.database=learnData_db

app.jwt.secret=learning-platform-secret-key-32chars-minimum-ok
app.jwt.expiry=86400000
